[dependencies]
deno = { path = "../core" }
deno_cli = { path = "../cli" }
futures = "0.3"

[lib]
crate-type = ["cdylib"]
path = "Source/lib.rs"

[package]
authors = ["the deno authors"]
edition = "2018"
name = "test_plugin"
publish = false
version = "0.0.1"
